apiVersion: external-secrets.io/v1
kind: ExternalSecret                                  # Defines an ExternalSecret to sync external secrets into Kubernetes Secrets.
metadata:
  name: backend-parameters
spec:
  refreshInterval: 1h                                 # How often the secrets should be refreshed.
  # References the SecretStore configuration for AWS Parameter Store.
  secretStoreRef:
    kind: SecretStore                                 # Specifies the type of SecretStore being used.
    name: aws-parameterstore                          # Defines the external secrets data to pull and sync into the Kubernetes Secret.
  data:  
  # Defines the secrets to fetch from the external provider and sync into the Kubernetes Secret.
    - secretKey: ENV_VAR5
      remoteRef:
        key: krci-cmtr-74cudwfj-backend-parameters  # Key in AWS Parameter Store containing the secret.
        property: backend-parameters.ENV_VAR5         # Sub-key in the AWS parameter to fetch.
    - secretKey: application.secret.properties.from.ps
      remoteRef:
        key: krci-cmtr-74cudwfj-backend-parameters
        property: backend-parameters.config
        decodingStrategy: Base64
