apiVersion: external-secrets.io/v1          # API version for the External Secrets resource.
kind: SecretStore                           # Defines a SecretStore, which configures how to retrieve secrets from an external provider.
metadata:
  name: aws-parameterstore                  # Name of the SecretStore.
spec:
  provider:
    aws:  # Specifies AWS as the external secrets provider.
      auth:
        jwt:  # Uses JWT authentication to communicate with AWS.
          serviceAccountRef:
            name: externalsecrets-aws       # References the Kubernetes ServiceAccount linked to an AWS IAM role.
      region: eu-central-1                  # Sets the AWS region where the Parameter Store is accessed.
      service: ParameterStore               # Specifies the AWS service to retrieve secrets from (e.g., Parameter Store).
